modLoader="javafml"
loaderVersion="[40,)"
license="Pineapple"

[[mods]]
modId="pineapple_delight"
version="${file.jarVersion}"
displayName="Pineapple Delight"
logoFile="assets/pineapple_delight/textures/pineapple_delight.png"
credits="Someoneice"
authors="Someoneice"
description='''
Add Pineapple to Minecraft!
'''

[[dependencies.pineapple_delight]]
modId="farmersdelight"
mandatory=true
versionRange="[*,)"
ordering="NONE"
side="BOTH"